{"n_dim": 55, "n_trials": 340, "objective": "risk_on_cube", "white": "pymoo_nsga2", "black": "dlib_default", "traceback": ["passing", "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 79, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/dlibcube.py\", line 28, in dlib_default_cube\n    best_x, best_val = find_min_global(_objective, lb, ub, n_trials)\nRuntimeError: \n\nError detected at line 63.\nError detected in file /private/var/folders/g2/6p5lz9hn36vbnv165bk7yj7r0000gn/T/pip-install-ojjogyqk/dlib_836e2179ea074a8ba6ce68fbb0be6025/tools/python/src/global_optimization.cpp.\nError detected in function double call_func(py::object, const matrix<double, 0, 1> &).\n\nFailing expression was 0 < num && num < 35.\nFunctions being optimized must take between 1 and 35 scalar arguments.\n\n"], "best_val": [183.1921392744184, null], "best_x": [[0.39633989842543926, 0.31870894703700026, 0.5264787753041993, 0.6487626766637107, 0.21797562592043068, 0.6213577310163383, 0.09533706828635899, 0.5592482498837441, 0.29331314592871005, 0.28516038491026463, 0.1466137720355216, 0.9132269393860198, 0.11917568556880347, 0.19498455634355538, 0.8534604922435045, 0.35999868375508093, 0.09289288931334089, 0.8840729132610361, 0.3371107415365462, 0.31502952131994555, 0.39416448496593703, 0.4333365945144644, 0.5275999970393975, 0.049161895955766755, 0.08954686551976432, 0.9491557016825296, 0.3193544813037029, 0.07719073533440296, 0.2522469024395142, 0.36870647546862284, 0.41454784635778774, 0.34647965865806446, 0.16284599347020967, 0.200875797370824, 0.3298172368445853, 0.2296605707856313, 0.043952098747647106, 0.6993921976012262, 0.5992810159983828, 0.34852572327983716, 0.24860129457188462, 0.29456382302160067, 0.1822109256431493, 0.06894814963971269, 0.0036833833669027427, 0.23433247033879703, 0.043270420060939396, 0.4176341822737119, 0.14419669376222702, 0.18020242472828218, 0.5745808858978488, 0.5412925463390843, 0.3571850762583997, 0.3200386858204948, 0.25478910185316683], null], "feval_count": [300, null], "n_trials_instructed": [237, 300], "passing": [true, false], "completed": false, "winner": "incomplete", "points": null}