{"name": ["shgo_slsqp_sobol_cube", "shgo_powell_sobol_cube", "shgo_nelder_sobol_cube", "scipy_slsqp_cube", "scipy_powell_cube", "scipy_nelder_cube", "scipy_lbfgsb_cube", "pysot_ei_cube", "pysot_lcb_cube", "pysot_random_cube", "pysot_srbf_cube", "pysot_dycors_cube", "ax_default_cube", "optuna_cmaes_cube", "optuna_tpe_cube", "optuna_random_cube", "optuna_random_cube_clone", "optuna_random_cube_clone_1", "optuna_random_cube_clone_2", "platypus_genetic_cube", "platypus_evolutionary_cube", "platypus_nsgaii_cube", "platypus_cmaes_cube", "platypus_gde3_cube", "platypus_ibea_cube", "platypus_moead_cube", "platypus_omopso_cube", "platypus_smpso_cube", "platypus_spea2_cube", "platypus_epsmoea_cube", "nevergrad_ngopt_cube", "nevergrad_ngopt4_cube", "nevergrad_de_cube", "nevergrad_portfolio_cube", "nevergrad_oneplus_cube", "nevergrad_hammersley_cube", "nevergrad_ngopt8_cube", "hyperopt_tpe_cube", "hyperopt_atpe_cube", "hyperopt_rand_cube", "pymoo_nelder_cube", "pymoo_nsga3_cube", "pymoo_unsga3_cube", "pymoo_pattern_cube", "pymoo_nsga2_cube", "pymoo_unsga3_cube", "skopt_gp_default_cube", "ultraopt_random_cube", "ultraopt_forest_cube", "ultraopt_gbrt_cube", "ultraopt_etpe_cube", "bayesopt_ucb_cube", "bayesopt_ei_cube", "bayesopt_poi_cube", "dlib_cube", "dlib_default_cube", "nlopt_direct_cube", "nlopt_ags_cube", "nlopt_esch_cube", "nlopt_isres_cube", "nlopt_crs2lm_cube", "nlopt_directr_cube", "nlopt_directo_cube", "nlopt_directl_cube", "bobyqa_default_cube", "bobyqa_noise_cube"], "count": [0, 0, 0, 22, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 44, 36, 36, 47, 31, 43, 34, 33, 0, 42, 33, 31, 36, 32, 28, 46, 30, 34, 24, 37, 41, 38, 31, 43, 35, 22, 28, 35, 59, 22, 29, 0, 0, 40, 43, 0, 46, 0, 0, 0, 0, 0, 43, 0, 39, 32, 39, 27, 35, 38, 43, 37], "rating": [1600, 1600, 1600, 1717.497861001083, 1600, 1906.494672596416, 1600, 1600, 1600, 1600, 1600, 1600, 1600, 1600, 1923.1309885235971, 1600, 1600, 1600, 1600, 1620.245609089785, 1780.5759662415735, 1609.2872865885276, 1600, 1252.6660015409013, 1741.5129012822104, 1337.0641132255726, 1774.4514422357502, 1441.5262757806704, 1368.7982270952418, 1876.2898957704542, 1986.7822575383598, 2021.6545847205089, 1672.0755796502292, 1467.6369802752836, 2129.921213674176, 1793.068097018181, 1964.5051499094175, 1750.391733428866, 1721.6148044831268, 1542.6431787034749, 1367.53293083888, 1427.1462810937267, 1414.4922903024026, 1425.6260987554417, 1567.8821555593672, 1600, 1600, 1263.5417474676326, 1603.3717915465957, 1600, 1954.2723309639205, 1600, 1600, 1600, 1600, 1600, 1456.3974630590703, 1600, 1950.5835462975158, 1346.4728626131807, 1352.813124056794, 1877.6139159074817, 1168.242837469968, 1096.3513106369523, 2119.4404310038904, 2065.1646926005187], "traceback": ["not yet run", "not yet run", "not yet run", "passing", "passing", "passing", "passing", "not yet run", "not yet run", "not yet run", "not yet run", "not yet run", "not yet run", "not yet run", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "not yet run", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "Black took 341 function evals when instructed to use 341", "passing", "passing", "passing", "passing", "not yet run", "not yet run", "passing", "passing", "not yet run", "passing", "not yet run", "not yet run", "not yet run", "passing", "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 43, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/dlibcube.py\", line 28, in dlib_default_cube\n    best_x, best_val = find_min_global(_objective, lb, ub, n_trials)\nRuntimeError: \n\nError detected at line 63.\nError detected in file /private/var/folders/g2/6p5lz9hn36vbnv165bk7yj7r0000gn/T/pip-install-ojjogyqk/dlib_836e2179ea074a8ba6ce68fbb0be6025/tools/python/src/global_optimization.cpp.\nError detected in function double call_func(py::object, const matrix<double, 0, 1> &).\n\nFailing expression was 0 < num && num < 35.\nFunctions being optimized must take between 1 and 35 scalar arguments.\n\n", "passing", "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 43, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/nloptcube.py\", line 43, in nlopt_ags_cube\n    return nlopt_cube_factory(objective=objective,n_trials=n_trials, n_dim=n_dim, with_count=with_count, method='gn_ags')\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/nloptcube.py\", line 32, in nlopt_cube_factory\n    best_x = opt.optimize([0.5] * n_dim)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/nlopt/nlopt.py\", line 334, in optimize\n    return _nlopt.opt_optimize(self, *args)\nValueError: nlopt invalid argument\n", "passing", "passing", "passing", "passing", "passing", "passing", "passing", "passing"], "active": [true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, true, true, true, false, false, true, true, true, true, true, true, true, true, true, true]}